export const UPDATE_MONTH = "UPDATE_MONTH";
export const UPDATE_YEAR = "UPDATE_YEAR";
export const GET_PREVIOUS_WEEK = "GET_PREVIOUS_WEEK";
export const GET_NEXT_WEEK = "GET_NEXT_WEEK";
export const UPDATE_CURRENT_WEEK = "UPDATE_CURRENT_WEEK";
export const ADD_DRUG = "ADD_DRUG";
